(ns com.github.matrixnorm.serene-hello.core
  ;(:require-macros [paren.serene :refer [def-specs]])
  (:require
    [clojure.spec.alpha :as s]
    [paren.serene.schema :refer [query] :rename {query introspection-query}]
    [paren.serene :refer [def-specs]]
    ["graphql" :as gql]))


(def schema-str "type Query { hello: String }")
(def schema (gql/buildSchema schema-str))
(def edn-schema
  (-> schema
      (gql/graphqlSync introspection-query)
      js/JSON.stringify
      js/JSON.parse
      (js->clj :keywordize-keys true)))
; See link below why all these JSON woodod
;https://stackoverflow.com/questions/34721251/inspect-by-new-constructed-javascript-objects-at-the-clojurescript-repl
(js/console.log edn-schema)


;(def-specs edn-schema {:prefix :gql})


;{:data {:__typename "Query",
;        :__schema {:__typename "__Schema",
;                   :queryType {:name "Query"},
;                   :mutationType nil,
;                   :subscriptionType nil,
;                   :directives [{:__typename "__Directive",
;                                 :args [{:__typename "__InputValue",
;                                         :defaultValue nil,
;                                         :description "Skipped when true.",
;                                         :name "if",
;                                         :type {:__typename "__Type",
;                                                :kind "NON_NULL",
;                                                :name nil,
;                                                :ofType {:__typename "__Type",
;                                                         :kind "SCALAR",
;                                                         :name "Boolean",
;                                                         :ofType nil}}}],
;                                 :description "Directs the executor to skip this field or fragment when the `if` argument is true.",
;                                 :locations ["FIELD" "FRAGMENT_SPREAD" "INLINE_FRAGMENT"],
;                                 :name "skip"}
;                                {:__typename "__Directive",
;                                 :args [{:__typename "__InputValue",
;                                         :defaultValue nil,
;                                         :description "Included when true.",
;                                         :name "if",
;                                         :type {:__typename "__Type",
;                                                :kind "NON_NULL",
;                                                :name nil,
;                                                :ofType {:__typename "__Type",
;                                                         :kind "SCALAR",
;                                                         :name "Boolean",
;                                                         :ofType nil}}}],
;                                 :description "Directs the executor to include this field or fragment only when the `if` argument is true.",
;                                 :locations ["FIELD" "FRAGMENT_SPREAD" "INLINE_FRAGMENT"],
;                                 :name "include"}
;                                {:__typename "__Directive",
;                                 :args [{:__typename "__InputValue",
;                                         :defaultValue "\"No longer supported\"",
;                                         :description "Explains why this element was deprecated, usually also including a suggestion for how to access supported similar data. Formatted using the Markdown syntax (as specified by [CommonMark](https://commonmark.org/).",
;                                         :name "reason",
;                                         :type {:__typename "__Type", :kind "SCALAR", :name "String", :ofType nil}}],
;                                 :description "Marks an element of a GraphQL schema as no longer supported.",
;                                 :locations ["FIELD_DEFINITION" "ENUM_VALUE"],
;                                 :name "deprecated"}],
;                   :types [{:description nil,
;                            :interfaces [],
;                            :__typename "__Type",
;                            :name "Query",
;                            :fields [{:__typename "__Field",
;                                      :args [],
;                                      :deprecationReason nil,
;                                      :description nil,
;                                      :isDeprecated false,
;                                      :name "hello",
;                                      :type {:__typename "__Type", :kind "SCALAR", :name "String", :ofType nil}}],
;                            :possibleTypes nil,
;                            :kind "OBJECT",
;                            :enumValues nil,
;                            :inputFields nil}
;                           {:description "The `String` scalar type represents textual data, represented as UTF-8 character sequences. The String type is most often used by GraphQL to represent free-form human-readable text.",
;                            :interfaces nil,
;                            :__typename "__Type",
;                            :name "String",
;                            :fields nil,
;                            :possibleTypes nil,
;                            :kind "SCALAR",
;                            :enumValues nil,
;                            :inputFields nil}
;                           {:description "A GraphQL Schema defines the capabilities of a GraphQL server. It exposes all available types and directives on the server, as well as the entry points for query, mutation, and subscription operations.",
;                            :interfaces [],
;                            :__typename "__Type",
;                            :name "__Schema",
;                            :fields [{:__typename "__Field",
;                                      :args [],
;                                      :deprecationReason nil,
;                                      :description "A list of all types supported by this server.",
;                                      :isDeprecated false,
;                                      :name "types",
;                                      :type {:__typename "__Type",
;                                             :kind "NON_NULL",
;                                             :name nil,
;                                             :ofType {:__typename "__Type",
;                                                      :kind "LIST",
;                                                      :name nil,
;                                                      :ofType {:__typename "__Type",
;                                                               :kind "NON_NULL",
;                                                               :name nil,
;                                                               :ofType {:__typename "__Type",
;                                                                        :kind "OBJECT",
;                                                                        :name "__Type",
;                                                                        :ofType nil}}}}}
;                                     {:__typename "__Field",
;                                      :args [],
;                                      :deprecationReason nil,
;                                      :description "The type that query operations will be rooted at.",
;                                      :isDeprecated false,
;                                      :name "queryType",
;                                      :type {:__typename "__Type",
;                                             :kind "NON_NULL",
;                                             :name nil,
;                                             :ofType {:__typename "__Type", :kind "OBJECT", :name "__Type", :ofType nil}}}
;                                     {:__typename "__Field",
;                                      :args [],
;                                      :deprecationReason nil,
;                                      :description "If this server supports mutation, the type that mutation operations will be rooted at.",
;                                      :isDeprecated false,
;                                      :name "mutationType",
;                                      :type {:__typename "__Type", :kind "OBJECT", :name "__Type", :ofType nil}}
;                                     {:__typename "__Field",
;                                      :args [],
;                                      :deprecationReason nil,
;                                      :description "If this server support subscription, the type that subscription operations will be rooted at.",
;                                      :isDeprecated false,
;                                      :name "subscriptionType",
;                                      :type {:__typename "__Type", :kind "OBJECT", :name "__Type", :ofType nil}}
;                                     {:__typename "__Field",
;                                      :args [],
;                                      :deprecationReason nil,
;                                      :description "A list of all directives supported by this server.",
;                                      :isDeprecated false,
;                                      :name "directives",
;                                      :type {:__typename "__Type",
;                                             :kind "NON_NULL",
;                                             :name nil,
;                                             :ofType {:__typename "__Type",
;                                                      :kind "LIST",
;                                                      :name nil,
;                                                      :ofType {:__typename "__Type",
;                                                               :kind "NON_NULL",
;                                                               :name nil,
;                                                               :ofType {:__typename "__Type",
;                                                                        :kind "OBJECT",
;                                                                        :name "__Directive",
;                                                                        :ofType nil}}}}}],
;                            :possibleTypes nil,
;                            :kind "OBJECT",
;                            :enumValues nil,
;                            :inputFields nil}
;                           {:description "The fundamental unit of any GraphQL Schema is the type. There are many kinds of types in GraphQL as represented by the `__TypeKind` enum.
;
;                                          Depending on the kind of a type, certain fields describe information about that type. Scalar types provide no information beyond a name and description, while Enum types provide their values. Object and Interface types provide the fields they describe. Abstract types, Union and Interface, provide the Object types possible at runtime. List and NonNull types compose other types.",
;                            :interfaces [],
;                            :__typename "__Type",
;                            :name "__Type",
;                            :fields [{:__typename "__Field",
;                                      :args [],
;                                      :deprecationReason nil,
;                                      :description nil,
;                                      :isDeprecated false,
;                                      :name "kind",
;                                      :type {:__typename "__Type",
;                                             :kind "NON_NULL",
;                                             :name nil,
;                                             :ofType {:__typename "__Type",
;                                                      :kind "ENUM",
;                                                      :name "__TypeKind",
;                                                      :ofType nil}}}
;                                     {:__typename "__Field",
;                                      :args [],
;                                      :deprecationReason nil,
;                                      :description nil,
;                                      :isDeprecated false,
;                                      :name "name",
;                                      :type {:__typename "__Type", :kind "SCALAR", :name "String", :ofType nil}}
;                                     {:__typename "__Field",
;                                      :args [],
;                                      :deprecationReason nil,
;                                      :description nil,
;                                      :isDeprecated false,
;                                      :name "description",
;                                      :type {:__typename "__Type", :kind "SCALAR", :name "String", :ofType nil}}
;                                     {:__typename "__Field",
;                                      :args [{:__typename "__InputValue",
;                                              :defaultValue "false",
;                                              :description nil,
;                                              :name "includeDeprecated",
;                                              :type {:__typename "__Type", :kind "SCALAR", :name "Boolean", :ofType nil}}],
;                                      :deprecationReason nil,
;                                      :description nil,
;                                      :isDeprecated false,
;                                      :name "fields",
;                                      :type {:__typename "__Type",
;                                             :kind "LIST",
;                                             :name nil,
;                                             :ofType {:__typename "__Type",
;                                                      :kind "NON_NULL",
;                                                      :name nil,
;                                                      :ofType {:__typename "__Type",
;                                                               :kind "OBJECT",
;                                                               :name "__Field",
;                                                               :ofType nil}}}}
;                                     {:__typename "__Field",
;                                      :args [],
;                                      :deprecationReason nil,
;                                      :description nil,
;                                      :isDeprecated false,
;                                      :name "interfaces",
;                                      :type {:__typename "__Type",
;                                             :kind "LIST",
;                                             :name nil,
;                                             :ofType {:__typename "__Type",
;                                                      :kind "NON_NULL",
;                                                      :name nil,
;                                                      :ofType {:__typename "__Type",
;                                                               :kind "OBJECT",
;                                                               :name "__Type",
;                                                               :ofType nil}}}}
;                                     {:__typename "__Field",
;                                      :args [],
;                                      :deprecationReason nil,
;                                      :description nil,
;                                      :isDeprecated false,
;                                      :name "possibleTypes",
;                                      :type {:__typename "__Type",
;                                             :kind "LIST",
;                                             :name nil,
;                                             :ofType {:__typename "__Type",
;                                                      :kind "NON_NULL",
;                                                      :name nil,
;                                                      :ofType {:__typename "__Type",
;                                                               :kind "OBJECT",
;                                                               :name "__Type",
;                                                               :ofType nil}}}}
;                                     {:__typename "__Field",
;                                      :args [{:__typename "__InputValue",
;                                              :defaultValue "false",
;                                              :description nil,
;                                              :name "includeDeprecated",
;                                              :type {:__typename "__Type", :kind "SCALAR", :name "Boolean", :ofType nil}}],
;                                      :deprecationReason nil,
;                                      :description nil,
;                                      :isDeprecated false,
;                                      :name "enumValues",
;                                      :type {:__typename "__Type",
;                                             :kind "LIST",
;                                             :name nil,
;                                             :ofType {:__typename "__Type",
;                                                      :kind "NON_NULL",
;                                                      :name nil,
;                                                      :ofType {:__typename "__Type",
;                                                               :kind "OBJECT",
;                                                               :name "__EnumValue",
;                                                               :ofType nil}}}}
;                                     {:__typename "__Field",
;                                      :args [],
;                                      :deprecationReason nil,
;                                      :description nil,
;                                      :isDeprecated false,
;                                      :name "inputFields",
;                                      :type {:__typename "__Type",
;                                             :kind "LIST",
;                                             :name nil,
;                                             :ofType {:__typename "__Type",
;                                                      :kind "NON_NULL",
;                                                      :name nil,
;                                                      :ofType {:__typename "__Type",
;                                                               :kind "OBJECT",
;                                                               :name "__InputValue",
;                                                               :ofType nil}}}}
;                                     {:__typename "__Field",
;                                      :args [],
;                                      :deprecationReason nil,
;                                      :description nil,
;                                      :isDeprecated false,
;                                      :name "ofType",
;                                      :type {:__typename "__Type", :kind "OBJECT", :name "__Type", :ofType nil}}],
;                            :possibleTypes nil,
;                            :kind "OBJECT",
;                            :enumValues nil,
;                            :inputFields nil}
;                           {:description "An enum describing what kind of type a given `__Type` is.",
;                            :interfaces nil,
;                            :__typename "__Type",
;                            :name "__TypeKind",
;                            :fields nil,
;                            :possibleTypes nil,
;                            :kind "ENUM",
;                            :enumValues [{:__typename "__EnumValue",
;                                          :deprecationReason nil,
;                                          :description "Indicates this type is a scalar.",
;                                          :isDeprecated false,
;                                          :name "SCALAR"}
;                                         {:__typename "__EnumValue",
;                                          :deprecationReason nil,
;                                          :description "Indicates this type is an object. `fields` and `interfaces` are valid fields.",
;                                          :isDeprecated false,
;                                          :name "OBJECT"}
;                                         {:__typename "__EnumValue",
;                                          :deprecationReason nil,
;                                          :description "Indicates this type is an interface. `fields` and `possibleTypes` are valid fields.",
;                                          :isDeprecated false,
;                                          :name "INTERFACE"}
;                                         {:__typename "__EnumValue",
;                                          :deprecationReason nil,
;                                          :description "Indicates this type is a union. `possibleTypes` is a valid field.",
;                                          :isDeprecated false,
;                                          :name "UNION"}
;                                         {:__typename "__EnumValue",
;                                          :deprecationReason nil,
;                                          :description "Indicates this type is an enum. `enumValues` is a valid field.",
;                                          :isDeprecated false,
;                                          :name "ENUM"}
;                                         {:__typename "__EnumValue",
;                                          :deprecationReason nil,
;                                          :description "Indicates this type is an input object. `inputFields` is a valid field.",
;                                          :isDeprecated false,
;                                          :name "INPUT_OBJECT"}
;                                         {:__typename "__EnumValue",
;                                          :deprecationReason nil,
;                                          :description "Indicates this type is a list. `ofType` is a valid field.",
;                                          :isDeprecated false,
;                                          :name "LIST"}
;                                         {:__typename "__EnumValue",
;                                          :deprecationReason nil,
;                                          :description "Indicates this type is a non-null. `ofType` is a valid field.",
;                                          :isDeprecated false,
;                                          :name "NON_NULL"}],
;                            :inputFields nil}
;                           {:description "The `Boolean` scalar type represents `true` or `false`.",
;                            :interfaces nil,
;                            :__typename "__Type",
;                            :name "Boolean",
;                            :fields nil,
;                            :possibleTypes nil,
;                            :kind "SCALAR",
;                            :enumValues nil,
;                            :inputFields nil}
;                           {:description "Object and Interface types are described by a list of Fields, each of which has a name, potentially a list of arguments, and a return type.",
;                            :interfaces [],
;                            :__typename "__Type",
;                            :name "__Field",
;                            :fields [{:__typename "__Field",
;                                      :args [],
;                                      :deprecationReason nil,
;                                      :description nil,
;                                      :isDeprecated false,
;                                      :name "name",
;                                      :type {:__typename "__Type",
;                                             :kind "NON_NULL",
;                                             :name nil,
;                                             :ofType {:__typename "__Type", :kind "SCALAR", :name "String", :ofType nil}}}
;                                     {:__typename "__Field",
;                                      :args [],
;                                      :deprecationReason nil,
;                                      :description nil,
;                                      :isDeprecated false,
;                                      :name "description",
;                                      :type {:__typename "__Type", :kind "SCALAR", :name "String", :ofType nil}}
;                                     {:__typename "__Field",
;                                      :args [],
;                                      :deprecationReason nil,
;                                      :description nil,
;                                      :isDeprecated false,
;                                      :name "args",
;                                      :type {:__typename "__Type",
;                                             :kind "NON_NULL",
;                                             :name nil,
;                                             :ofType {:__typename "__Type",
;                                                      :kind "LIST",
;                                                      :name nil,
;                                                      :ofType {:__typename "__Type",
;                                                               :kind "NON_NULL",
;                                                               :name nil,
;                                                               :ofType {:__typename "__Type",
;                                                                        :kind "OBJECT",
;                                                                        :name "__InputValue",
;                                                                        :ofType nil}}}}}
;                                     {:__typename "__Field",
;                                      :args [],
;                                      :deprecationReason nil,
;                                      :description nil,
;                                      :isDeprecated false,
;                                      :name "type",
;                                      :type {:__typename "__Type",
;                                             :kind "NON_NULL",
;                                             :name nil,
;                                             :ofType {:__typename "__Type", :kind "OBJECT", :name "__Type", :ofType nil}}}
;                                     {:__typename "__Field",
;                                      :args [],
;                                      :deprecationReason nil,
;                                      :description nil,
;                                      :isDeprecated false,
;                                      :name "isDeprecated",
;                                      :type {:__typename "__Type",
;                                             :kind "NON_NULL",
;                                             :name nil,
;                                             :ofType {:__typename "__Type",
;                                                      :kind "SCALAR",
;                                                      :name "Boolean",
;                                                      :ofType nil}}}
;                                     {:__typename "__Field",
;                                      :args [],
;                                      :deprecationReason nil,
;                                      :description nil,
;                                      :isDeprecated false,
;                                      :name "deprecationReason",
;                                      :type {:__typename "__Type", :kind "SCALAR", :name "String", :ofType nil}}],
;                            :possibleTypes nil,
;                            :kind "OBJECT",
;                            :enumValues nil,
;                            :inputFields nil}
;                           {:description "Arguments provided to Fields or Directives and the input fields of an InputObject are represented as Input Values which describe their type and optionally a default value.",
;                            :interfaces [],
;                            :__typename "__Type",
;                            :name "__InputValue",
;                            :fields [{:__typename "__Field",
;                                      :args [],
;                                      :deprecationReason nil,
;                                      :description nil,
;                                      :isDeprecated false,
;                                      :name "name",
;                                      :type {:__typename "__Type",
;                                             :kind "NON_NULL",
;                                             :name nil,
;                                             :ofType {:__typename "__Type", :kind "SCALAR", :name "String", :ofType nil}}}
;                                     {:__typename "__Field",
;                                      :args [],
;                                      :deprecationReason nil,
;                                      :description nil,
;                                      :isDeprecated false,
;                                      :name "description",
;                                      :type {:__typename "__Type", :kind "SCALAR", :name "String", :ofType nil}}
;                                     {:__typename "__Field",
;                                      :args [],
;                                      :deprecationReason nil,
;                                      :description nil,
;                                      :isDeprecated false,
;                                      :name "type",
;                                      :type {:__typename "__Type",
;                                             :kind "NON_NULL",
;                                             :name nil,
;                                             :ofType {:__typename "__Type", :kind "OBJECT", :name "__Type", :ofType nil}}}
;                                     {:__typename "__Field",
;                                      :args [],
;                                      :deprecationReason nil,
;                                      :description "A GraphQL-formatted string representing the default value for this input value.",
;                                      :isDeprecated false,
;                                      :name "defaultValue",
;                                      :type {:__typename "__Type", :kind "SCALAR", :name "String", :ofType nil}}],
;                            :possibleTypes nil,
;                            :kind "OBJECT",
;                            :enumValues nil,
;                            :inputFields nil}
;                           {:description "One possible value for a given Enum. Enum values are unique values, not a placeholder for a string or numeric value. However an Enum value is returned in a JSON response as a string.",
;                            :interfaces [],
;                            :__typename "__Type",
;                            :name "__EnumValue",
;                            :fields [{:__typename "__Field",
;                                      :args [],
;                                      :deprecationReason nil,
;                                      :description nil,
;                                      :isDeprecated false,
;                                      :name "name",
;                                      :type {:__typename "__Type",
;                                             :kind "NON_NULL",
;                                             :name nil,
;                                             :ofType {:__typename "__Type", :kind "SCALAR", :name "String", :ofType nil}}}
;                                     {:__typename "__Field",
;                                      :args [],
;                                      :deprecationReason nil,
;                                      :description nil,
;                                      :isDeprecated false,
;                                      :name "description",
;                                      :type {:__typename "__Type", :kind "SCALAR", :name "String", :ofType nil}}
;                                     {:__typename "__Field",
;                                      :args [],
;                                      :deprecationReason nil,
;                                      :description nil,
;                                      :isDeprecated false,
;                                      :name "isDeprecated",
;                                      :type {:__typename "__Type",
;                                             :kind "NON_NULL",
;                                             :name nil,
;                                             :ofType {:__typename "__Type",
;                                                      :kind "SCALAR",
;                                                      :name "Boolean",
;                                                      :ofType nil}}}
;                                     {:__typename "__Field",
;                                      :args [],
;                                      :deprecationReason nil,
;                                      :description nil,
;                                      :isDeprecated false,
;                                      :name "deprecationReason",
;                                      :type {:__typename "__Type", :kind "SCALAR", :name "String", :ofType nil}}],
;                            :possibleTypes nil,
;                            :kind "OBJECT",
;                            :enumValues nil,
;                            :inputFields nil}
;                           {:description "A Directive provides a way to describe alternate runtime execution and type validation behavior in a GraphQL document.
;
;                                          In some cases, you need to provide options to alter GraphQL's execution behavior in ways field arguments will not suffice, such as conditionally including or skipping a field. Directives provide this by describing additional information to the executor.",
;                            :interfaces [],
;                            :__typename "__Type",
;                            :name "__Directive",
;                            :fields [{:__typename "__Field",
;                                      :args [],
;                                      :deprecationReason nil,
;                                      :description nil,
;                                      :isDeprecated false,
;                                      :name "name",
;                                      :type {:__typename "__Type",
;                                             :kind "NON_NULL",
;                                             :name nil,
;                                             :ofType {:__typename "__Type", :kind "SCALAR", :name "String", :ofType nil}}}
;                                     {:__typename "__Field",
;                                      :args [],
;                                      :deprecationReason nil,
;                                      :description nil,
;                                      :isDeprecated false,
;                                      :name "description",
;                                      :type {:__typename "__Type", :kind "SCALAR", :name "String", :ofType nil}}
;                                     {:__typename "__Field",
;                                      :args [],
;                                      :deprecationReason nil,
;                                      :description nil,
;                                      :isDeprecated false,
;                                      :name "locations",
;                                      :type {:__typename "__Type",
;                                             :kind "NON_NULL",
;                                             :name nil,
;                                             :ofType {:__typename "__Type",
;                                                      :kind "LIST",
;                                                      :name nil,
;                                                      :ofType {:__typename "__Type",
;                                                               :kind "NON_NULL",
;                                                               :name nil,
;                                                               :ofType {:__typename "__Type",
;                                                                        :kind "ENUM",
;                                                                        :name "__DirectiveLocation",
;                                                                        :ofType nil}}}}}
;                                     {:__typename "__Field",
;                                      :args [],
;                                      :deprecationReason nil,
;                                      :description nil,
;                                      :isDeprecated false,
;                                      :name "args",
;                                      :type {:__typename "__Type",
;                                             :kind "NON_NULL",
;                                             :name nil,
;                                             :ofType {:__typename "__Type",
;                                                      :kind "LIST",
;                                                      :name nil,
;                                                      :ofType {:__typename "__Type",
;                                                               :kind "NON_NULL",
;                                                               :name nil,
;                                                               :ofType {:__typename "__Type",
;                                                                        :kind "OBJECT",
;                                                                        :name "__InputValue",
;                                                                        :ofType nil}}}}}],
;                            :possibleTypes nil,
;                            :kind "OBJECT",
;                            :enumValues nil,
;                            :inputFields nil}
;                           {:description "A Directive can be adjacent to many parts of the GraphQL language, a __DirectiveLocation describes one such possible adjacencies.",
;                            :interfaces nil,
;                            :__typename "__Type",
;                            :name "__DirectiveLocation",
;                            :fields nil,
;                            :possibleTypes nil,
;                            :kind "ENUM",
;                            :enumValues [{:__typename "__EnumValue",
;                                          :deprecationReason nil,
;                                          :description "Location adjacent to a query operation.",
;                                          :isDeprecated false,
;                                          :name "QUERY"}
;                                         {:__typename "__EnumValue",
;                                          :deprecationReason nil,
;                                          :description "Location adjacent to a mutation operation.",
;                                          :isDeprecated false,
;                                          :name "MUTATION"}
;                                         {:__typename "__EnumValue",
;                                          :deprecationReason nil,
;                                          :description "Location adjacent to a subscription operation.",
;                                          :isDeprecated false,
;                                          :name "SUBSCRIPTION"}
;                                         {:__typename "__EnumValue",
;                                          :deprecationReason nil,
;                                          :description "Location adjacent to a field.",
;                                          :isDeprecated false,
;                                          :name "FIELD"}
;                                         {:__typename "__EnumValue",
;                                          :deprecationReason nil,
;                                          :description "Location adjacent to a fragment definition.",
;                                          :isDeprecated false,
;                                          :name "FRAGMENT_DEFINITION"}
;                                         {:__typename "__EnumValue",
;                                          :deprecationReason nil,
;                                          :description "Location adjacent to a fragment spread.",
;                                          :isDeprecated false,
;                                          :name "FRAGMENT_SPREAD"}
;                                         {:__typename "__EnumValue",
;                                          :deprecationReason nil,
;                                          :description "Location adjacent to an inline fragment.",
;                                          :isDeprecated false,
;                                          :name "INLINE_FRAGMENT"}
;                                         {:__typename "__EnumValue",
;                                          :deprecationReason nil,
;                                          :description "Location adjacent to a variable definition.",
;                                          :isDeprecated false,
;                                          :name "VARIABLE_DEFINITION"}
;                                         {:__typename "__EnumValue",
;                                          :deprecationReason nil,
;                                          :description "Location adjacent to a schema definition.",
;                                          :isDeprecated false,
;                                          :name "SCHEMA"}
;                                         {:__typename "__EnumValue",
;                                          :deprecationReason nil,
;                                          :description "Location adjacent to a scalar definition.",
;                                          :isDeprecated false,
;                                          :name "SCALAR"}
;                                         {:__typename "__EnumValue",
;                                          :deprecationReason nil,
;                                          :description "Location adjacent to an object type definition.",
;                                          :isDeprecated false,
;                                          :name "OBJECT"}
;                                         {:__typename "__EnumValue",
;                                          :deprecationReason nil,
;                                          :description "Location adjacent to a field definition.",
;                                          :isDeprecated false,
;                                          :name "FIELD_DEFINITION"}
;                                         {:__typename "__EnumValue",
;                                          :deprecationReason nil,
;                                          :description "Location adjacent to an argument definition.",
;                                          :isDeprecated false,
;                                          :name "ARGUMENT_DEFINITION"}
;                                         {:__typename "__EnumValue",
;                                          :deprecationReason nil,
;                                          :description "Location adjacent to an interface definition.",
;                                          :isDeprecated false,
;                                          :name "INTERFACE"}
;                                         {:__typename "__EnumValue",
;                                          :deprecationReason nil,
;                                          :description "Location adjacent to a union definition.",
;                                          :isDeprecated false,
;                                          :name "UNION"}
;                                         {:__typename "__EnumValue",
;                                          :deprecationReason nil,
;                                          :description "Location adjacent to an enum definition.",
;                                          :isDeprecated false,
;                                          :name "ENUM"}
;                                         {:__typename "__EnumValue",
;                                          :deprecationReason nil,
;                                          :description "Location adjacent to an enum value definition.",
;                                          :isDeprecated false,
;                                          :name "ENUM_VALUE"}
;                                         {:__typename "__EnumValue",
;                                          :deprecationReason nil,
;                                          :description "Location adjacent to an input object type definition.",
;                                          :isDeprecated false,
;                                          :name "INPUT_OBJECT"}
;                                         {:__typename "__EnumValue",
;                                          :deprecationReason nil,
;                                          :description "Location adjacent to an input object field definition.",
;                                          :isDeprecated false,
;                                          :name "INPUT_FIELD_DEFINITION"}],
;                            :inputFields nil}]}}}